export const productData = [
  {
    id: 1,
    name: "Pommes",
    category: "fruit",
    price: 1.99,
    img: "../img/apples.png",
  },
  {
    id: 2,
    name: "Poires",
    category: "fruit",
    price: 3.99,
    img: "../img/pears.png",
  },
  {
    id: 3,
    name: "Comté",
    category: "freshProduct",
    price: 4.22,
    img: "../img/comte.png",
  },
  {
    id: 4,
    name: "Jus d'orange",
    category: "beverage",
    price: 2.29,
    img: "../img/orange-juice.png",
  },
  {
    id: 5,
    name: "Yaourt Bio",
    category: "freshProduct",
    price: 1.09,
    img: "../img/yogourt.png",
  },
  {
    id: 6,
    name: "Beurre Moulé",
    category: "freshProduct",
    price: 1.09,
    img: "../img/butter.png",
  },
  {
    id: 7,
    name: "Coca Cola 1.25L",
    category: "beverage",
    price: 1.25,
    img: "../img/coca-cola.png",
  },
  {
    id: 8,
    name: "Salade Batavia",
    category: "vegetable",
    price: 0.99,
    img: "../img/salad.png",
  },
  {
    id: 9,
    name: "Radis",
    category: "vegetable",
    price: 1.29,
    img: "../img/radish.png",
  },
];
